Add healthcheck

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,6 +40,16 @@ jobs:
             export IMAGE_TAG=${{ github.sha }}
             docker compose up -d --force-recreate
 
+            echo "-- Health check --"
+            sleep 3
+
+            CONTAINER_ID=$(docker ps --filter "name=rails_app_pro" --format="{{.ID}}")
+
+            if ! docker exec "$CONTAINER_ID" curl -f http://localhost:3000; then
+              echo "Health check failed! Rolling back..."
+              exit 1
+            fi
+
             echo "-- Find container --"
             CONTAINER_ID=$(docker ps --filter "name=rails_app_pro" --format="{{.ID}}")
 
